name: Setup Python with UV
description: Checkout, install UV, setup Python, install deps

inputs:
  python-version:
    description: Python version to install
    default: "3.10"
  fetch-depth:
    description: Git fetch depth
    default: "1"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - uses: astral-sh/setup-uv@v3

    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
        restore-keys: ${{ runner.os }}-uv-

    - name: Setup Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install dependencies
      run: uv sync --frozen
      shell: bash
